# Generated by Django 5.2.2 on 2026-02-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('employee_id', models.CharField(max_length=64, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('coupon', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Table_Registration',
            },
        ),
    ]
