# Generated by Django 5.2.2 on 2026-02-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('establishment_year', models.PositiveIntegerField()),
                ('owner_type', models.CharField(choices=[('proprietor', 'Proprietor'), ('partnership', 'Partnership'), ('private_ltd', 'Private Limited'), ('public_ltd', 'Public Limited'), ('llp', 'LLP'), ('other', 'Other')])),
                ('annual_turnover', models.CharField(blank=True, choices=[('0_10L', '0 - 10 Lakhs'), ('10_50L', '10 - 50 Lakhs'), ('50L_1CR', '50 Lakhs - 1 Crore'), ('1CR_PLUS', 'Above 1 Crore')], max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('nature_of_business', models.CharField(max_length=64)),
                ('number_of_branches', models.PositiveIntegerField()),
                ('employee_count', models.CharField(choices=[('1_10', '1 - 10 Employees'), ('11_50', '11 - 50 Employees'), ('51_200', '51 - 200 Employees'), ('201_500', '201 - 500 Employees'), ('500_plus', 'Above 500')])),
                ('number_of_employees', models.PositiveIntegerField()),
                ('company_pan', models.CharField(max_length=10, unique=True)),
                ('company_gst', models.CharField(max_length=15, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='Registration_Form.registration')),
            ],
            options={
                'db_table': 'Table_Registration',
            },
        ),
    ]
